### ISSUE TITLE
Allow deep linking of a map view.

### ISSUE THREAD

**Issue by fgregg** [open-city/second-city-zoning#12]
I wanted to highlight an unusual zoning request in city council, and was hoping I would be able to link to the view of the map.

**Comment by derekeder** [comment]
You mean like this? http://secondcityzoning.org/#/?id=9670

**Comment by fgregg** [comment]
I love the deep linking to the zoning areas. But, I mean't something with
at lat/long zoom level. Something that would allow
https://github.com/open-city/councilmatic/issues/70

**Comment by derekeder** [comment]
This is satisfied by deep linking address searches like so: http://secondcityzoning.org/#/?address=11146%20S%20Michigan%20Ave%2C%20Chicago%2C%20IL%2C%20United%20States&id=11037

**Comment by fgregg** [comment]
duh!
