### ISSUE TITLE
Add zoning district boundaries

### ISSUE THREAD

**Issue by jpvelez** [open-city/second-city-zoning#5]
Right now the map is only color according to broad zoning categories - Residential, Commercial, etc.

It would be great if the boundaries of all zoning districts would be visible at low zoom levels. They could be a lighter dark color than the current category boundaries. That way all of the one-parcel zoning changes aldermen do could be visible on the map. They're currently hidden.

**Comment by derekeder** [comment]
Done, I believe a while ago.
